version: 2.1

orbs:
  aws-cli: circleci/aws-cli@5.4.1

jobs:
  generate-and-deploy-schema:
    docker:
      - image: cimg/base:2024.02
    steps:
      - checkout
      - aws-cli/setup
      - run:
          name: Install jq
          command: |
            sudo apt-get update
            sudo apt-get install -y jq
      - run:
          name: Set Key and Generate Schema
          command: |
            # Export key for OpenAPI spec generation
            export OPENAPI_SPEC_GEN=true
            echo "OPENAPI_SPEC_GEN=$OPENAPI_SPEC_GEN" >> $BASH_ENV
            make dev
      - run:
          name: Upload Swagger files and Compose via SSM
          command: |
            # Base64 encode files for upload
            SCHEMA_FILE=$(base64 -w 0 schema.yaml)
            COMPOSE_FILE=$(base64 -w 0 swagger-compose.yml)
            SAAS_FILE=$(base64 -w 0 specs/saas.yml)
            IIFL_FILE=$(base64 -w 0 specs/iifl.yml)

            command_id=$(aws ssm send-command \
              --instance-ids "$EC2_INSTANCE_ID" \
              --document-name "AWS-RunShellScript" \
              --comment "Upload Swagger files and start via Docker Compose" \
              --parameters "commands=[
                \"bash -c 'set -e;
                  trap \\\"echo SCHEMA_UPLOAD_FAILURE 1>&2\\\" ERR;
                  mkdir -p /home/ubuntu/swagger/specs;
                  echo \\\"$SCHEMA_FILE\\\"  | base64 -d > /home/ubuntu/swagger/specs/schema.yaml;
                  echo \\\"$SAAS_FILE\\\"    | base64 -d > /home/ubuntu/swagger/specs/saas.yml;
                  echo \\\"$IIFL_FILE\\\"    | base64 -d > /home/ubuntu/swagger/specs/iifl.yml;
                  trap \\\"echo COMPOSE_UPLOAD_FAILURE 1>&2\\\" ERR;
                  echo \\\"$COMPOSE_FILE\\\" | base64 -d > /home/ubuntu/swagger/swagger-compose.yml;
                  cd /home/ubuntu/swagger;
                  trap \\\"echo DOCKER_COMPOSE_DOWN_FAILURE 1>&2\\\" ERR;
                  docker compose -f swagger-compose.yml down || true;
                  trap \\\"echo DOCKER_COMPOSE_UP_FAILURE 1>&2\\\" ERR;
                  docker compose -f swagger-compose.yml up -d;
                '\" 
              ]" \
              --region "$AWS_REGION" \
              --query 'Command.CommandId' --output text)

            echo "Command ID: $command_id"
            echo "export command_id=$command_id" >> $BASH_ENV
      - run:
          name: Wait for SSM Command to Complete
          command: |
            aws ssm wait command-executed \
              --command-id $command_id \
              --instance-id "$EC2_INSTANCE_ID" \
              --region "$AWS_REGION" || true
      - run:
          name: Fetch SSM Output and Check Status
          command: |
            ssm_output=$(aws ssm get-command-invocation \
              --command-id $command_id \
              --instance-id "$EC2_INSTANCE_ID" \
              --region "$AWS_REGION")
            status=$(echo "$ssm_output" | jq -r '.Status')
            stdout=$(echo "$ssm_output" | jq -r '.StandardOutputContent')
            stderr=$(echo "$ssm_output" | jq -r '.StandardErrorContent')
            echo "Status: $status"
            echo "Standard Output: $stdout"
            echo "Standard Error: $stderr"
            if [ "$status" != "Success" ]; then
              echo "Swagger UI deployment failed"
              exit 1
            fi  

workflows:
  version: 2
  deploy-swagger-ui:
    jobs:
      - generate-and-deploy-schema