version: 2.1

jobs:
  generate-and-deploy-schema:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - $GITHUB_SSH_FINGERPRINT
      - run:
          name: Set up Dev Environment & Generate Schema
          command: make dev
      - run:
          name: Copy schema.yaml to EC2
          command: |
            ssh -o StrictHostKeyChecking=no ubuntu@$EC2_HOST "mkdir -p /home/ubuntu/swagger"
            scp -o StrictHostKeyChecking=no schema.yaml ubuntu@$EC2_HOST:/home/ubuntu/swagger/schema.yaml
      - run:
          name: Start Swagger UI
          command: |
            ssh -o StrictHostKeyChecking=no ubuntu@$EC2_HOST "
              docker rm -f swagger-ui || true &&
              docker run -d -p 8080:8080 \
                -e SWAGGER_JSON=/schema.yaml \
                -v /home/ubuntu/swagger/schema.yaml:/schema.yaml \
                --name swagger-ui \
                swaggerapi/swagger-ui
            "

workflows:
  version: 2
  deploy-swagger-ui:
    jobs:
      - generate-and-deploy-schema