version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.10  # Python environment

    steps:
      - checkout

      # Add SSH key for EC2 access
      - add_ssh_keys:
          fingerprints:
            - "SHA256:Tk0ytmU5TINUYGptlcwxJLPXIdkxAiVAc5fV2Lz5USM"  # Replace with your CircleCI SSH key fingerprint

      # Setup Python environment and install dependencies
      - run:
          name: Set up Python
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt

      # Run Django migrations
      - run:
          name: Migrate Database
          command: |
            . venv/bin/activate
            python manage.py migrate

      # Generate schema.yaml using drf-spectacular
      - run:
          name: Generate schema.yaml
          command: |
            . venv/bin/activate
            python manage.py spectacular --file schema.yaml

      # Copy schema.yaml to EC2 (create folder if not exists)
      - run:
          name: Copy schema.yaml to EC2
          command: |
            ssh -o StrictHostKeyChecking=no ubuntu@<EC2-PUBLIC-IP> "mkdir -p /home/ubuntu/swagger"
            scp -o StrictHostKeyChecking=no schema.yaml ubuntu@<EC2-PUBLIC-IP>:/home/ubuntu/swagger/schema.yaml

      # Run Swagger UI Docker container on EC2
      - run:
          name: Start Swagger UI
          command: |
            ssh -o StrictHostKeyChecking=no ubuntu@<EC2-PUBLIC-IP> "
              docker rm -f swagger-ui || true &&
              docker run -d -p 8080:8080 \
                -e SWAGGER_JSON=/schema.yaml \
                -v /home/ubuntu/swagger/schema.yaml:/schema.yaml \
                --name swagger-ui \
                swaggerapi/swagger-ui
            "

workflows:
  version: 2
  generate-and-deploy-schema:
    jobs:
      - build