version: 2.1

jobs:
  build-and-deploy:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout

      # Add SSH keys if deploying to EC2
      - add_ssh_keys:
          fingerprints:
            - $GITHUB_SSH_FINGERPRINT

      # Run Makefile to setup venv, install dependencies, migrate DB, generate schema
      - run:
          name: Set up Dev Environment & Generate Schema
          command: make dev

      # Copy schema.yaml to EC2
      - run:
          name: Copy schema.yaml to EC2
          command: |
            ssh -o StrictHostKeyChecking=no ubuntu@$EC2_HOST "mkdir -p /home/ubuntu/swagger"
            scp -o StrictHostKeyChecking=no schema.yaml ubuntu@$EC2_HOST:/home/ubuntu/swagger/schema.yaml

      # Start Swagger UI Docker container on EC2
      - run:
          name: Start Swagger UI
          command: |
            ssh -o StrictHostKeyChecking=no ubuntu@$EC2_HOST "
              docker rm -f swagger-ui || true &&
              docker run -d -p 8080:8080 \
                -e SWAGGER_JSON=/schema.yaml \
                -v /home/ubuntu/swagger/schema.yaml:/schema.yaml \
                --name swagger-ui \
                swaggerapi/swagger-ui
            "

workflows:
  version: 2
  generate-and-deploy-schema:
    jobs:
      - build-and-deploy